import inspect
from yail.logic import LoggerLevel as LoggerLevel

APP_NAME: str
LOGGER_NAME: str

def date_func(*args) -> str: ...
def package_func(frame: inspect.FrameInfo, *args) -> str: ...
def package_func_functions(frame, show: str) -> str: ...
def msg_func(*args) -> str: ...
def data_func(*args): ...
def loglevel_func(level: LoggerLevel, what: str) -> str: ...
def lineno_func(frame: inspect.FrameInfo, *args): ...
def logger_func(data: str, name: str) -> str: ...
